import { ArrowUpRight } from "lucide-react";
import { projects } from "@/data/projects";
import { Container } from "@/components/ui/Container";
import { Reveal } from "@/components/ui/Reveal";
import { SectionHeading } from "@/components/ui/SectionHeading";

function ProjectVisual({ theme }: { theme: string }) {
  if (theme === "website") return <div className="h-full rounded-2xl bg-white p-4"><div className="flex gap-1.5 border-b border-line pb-3"><i className="size-2 rounded-full bg-[#ff766c]"/><i className="size-2 rounded-full bg-[#ffcb4c]"/><i className="size-2 rounded-full bg-teal"/></div><div className="grid h-[calc(100%-20px)] grid-cols-[.9fr_1.1fr] items-center gap-5"><div><div className="h-2 w-14 rounded bg-brand/20"/><div className="mt-3 h-4 w-full rounded bg-deep"/><div className="mt-2 h-4 w-3/4 rounded bg-deep"/><div className="mt-4 h-7 w-20 rounded-full bg-teal"/></div><div className="h-28 rounded-xl bg-gradient-to-br from-skywash to-teal/25"/></div></div>;
  if (theme === "brand") return <div className="relative h-full overflow-hidden rounded-2xl bg-deep"><div className="absolute -right-8 -top-8 size-32 rounded-full bg-teal"/><div className="absolute bottom-5 left-5 text-white"><div className="mb-5 grid size-12 place-items-center rounded-xl border border-white/20 text-xl font-black">D</div><p className="text-xs font-bold uppercase tracking-[.2em] text-teal">Visual system</p><p className="mt-2 text-2xl font-extrabold">Bold. Clear.<br/>Consistent.</p></div></div>;
  return <div className="h-full rounded-2xl bg-gradient-to-br from-brand to-deep p-5 text-white"><div className="mx-auto h-full max-w-[155px] rounded-[20px] border-4 border-white/20 bg-white p-3 text-deep"><div className="mx-auto h-1 w-8 rounded bg-line"/><p className="mt-6 text-[8px] font-bold uppercase tracking-wider text-brand">Your queue</p><p className="mt-2 text-4xl font-extrabold">04</p><div className="mt-4 h-1.5 overflow-hidden rounded-full bg-line"><div className="h-full w-2/3 bg-teal"/></div><div className="mt-5 rounded-lg bg-cloud p-2 text-[8px] font-bold">Live position tracking</div></div></div>;
}

export function Portfolio() { return <section className="section-pad bg-white"><Container><Reveal><SectionHeading eyebrow="Our work" title="Selected Work" text="A look at our product thinking and clearly labelled concept work. Real project case studies can be added as the portfolio grows." /></Reveal><div className="mt-12 grid gap-5 lg:grid-cols-3">{projects.map((project, i) => <Reveal key={project.title} delay={i * .07}><article className="group h-full overflow-hidden rounded-[26px] border border-line bg-white p-3 transition hover:-translate-y-1 hover:shadow-[0_22px_55px_rgba(3,31,75,.09)]"><div className="h-64 rounded-[19px] bg-cloud p-4"><ProjectVisual theme={project.theme}/></div><div className="p-4 pb-5"><span className="text-[10px] font-extrabold uppercase tracking-[.17em] text-brand">{project.tag}</span><div className="mt-3 flex items-start justify-between gap-4"><div><h3 className="text-xl font-extrabold text-deep">{project.title}</h3><p className="mt-1 text-sm font-semibold text-muted">{project.type}</p></div><ArrowUpRight className="shrink-0 text-teal transition group-hover:translate-x-0.5 group-hover:-translate-y-0.5" size={20}/></div><p className="mt-4 text-sm leading-6 text-muted">{project.description}</p></div></article></Reveal>)}</div></Container></section>; }
