import { ArrowUpRight, Check } from "lucide-react";
import { services } from "@/data/services";
import { Container } from "@/components/ui/Container";
import { Reveal } from "@/components/ui/Reveal";
import { SectionHeading } from "@/components/ui/SectionHeading";

export function Services() {
  return <section id="services" className="section-pad bg-white"><Container><Reveal><SectionHeading eyebrow="What we do" title="Everything You Need to Build Your Digital Presence" text="Strategy, design, technology and content — brought together under one team." /></Reveal><div className="mt-14 grid gap-5 md:grid-cols-2 lg:grid-cols-3">{services.map((service, i) => { const Icon = service.icon; return <Reveal key={service.title} delay={(i % 3) * .06}><article className="group flex h-full flex-col rounded-[26px] border border-line bg-white p-6 transition duration-300 hover:-translate-y-1.5 hover:border-brand/25 hover:shadow-[0_22px_55px_rgba(3,31,75,.09)] sm:p-7"><div className="flex items-center justify-between"><span className="grid size-12 place-items-center rounded-2xl bg-skywash text-brand transition group-hover:bg-brand group-hover:text-white"><Icon size={22} /></span><span className="text-xs font-extrabold tracking-[.18em] text-brand/55">{service.number}</span></div><h3 className="mt-7 text-xl font-extrabold tracking-[-.025em] text-deep">{service.title}</h3><p className="mt-3 min-h-[72px] text-sm leading-6 text-muted">{service.description}</p><ul className="mt-5 space-y-2.5">{service.features.map((feature) => <li key={feature} className="flex items-center gap-2 text-sm font-medium text-ink/80"><Check size={15} className="text-teal" />{feature}</li>)}</ul><a href="#contact" aria-label={`Learn more about ${service.title}`} className="mt-7 inline-flex items-center gap-2 text-sm font-extrabold text-brand">Learn More <ArrowUpRight size={16} className="transition group-hover:translate-x-0.5 group-hover:-translate-y-0.5" /></a></article></Reveal>; })}</div></Container></section>;
}
